// Code generated by nothing at all. DO NOT EDIT.

package main

import (
	"strconv"
	"context"
)

// Generated is what a generator wrote, and the fixer leaves the block above it
// exactly as it found it.
func Generated(ctx context.Context, n int) string {
	_ = ctx
	return strconv.Itoa(n)
}
