---
version: "3"

# Running this taskfile ensures that markdowns are
# consistently formatted according to mdox rules.

includes:
  mdox: ./Taskfile.mdox.yml

tasks:
  up:
    desc: "Bring up docker env"
    cmd: docker compose up -d

  down:
    desc: "Bring down docker env"
    cmd: docker compose down