---
version: "3"

environment:
  CGO_ENABLED: 0

tasks:
  default:
    desc: "Everything"
    cmds:
      - task: fmt
      - task: test
      - task: build
      - task: build:test

  fmt:
    desc: "Format sources"
    cmds:
      - goimports -w .
      - go fmt ./...

  test:
    desc: "Run tests"
    cmds:
      - gotestsum ./... -- -count 1

  build:
    desc: "Run build"
    cmds:
      - go install .

  build:test:
    desc: "Test build"
    cmds:
      - gofsck ./...

  clean:
    desc: "Clean build artifacts and generated files"
    cmds:
      - rm -f gofsck gofsck.so
      - rm -f go-fsck.db go-fsck.json
      - rm -f golangci-lint.json report.json
      - rm -rf ../docs_backup/
