---
version: "3"

environment:
  CGO_ENABLED: 1

tasks:
  default:
    desc: "Everything"
    cmds:
      - task: fmt
      - task: test
      - task: build
      - task: build:test

  fmt:
    desc: "Format sources"
    cmds:
      - goimports -w .
      - go fmt ./...

  test:
    desc: "Run tests"
    cmds:
      - go test -count=1 -v ./...

  build:
    desc: "Run build"
    cmds:
      - go install .
      - go build -buildmode=plugin -o gofsck.so .

  build:test:
    desc: "Test build"
    cmds:
      - golangci-lint cache clean
      - cd src && golangci-lint run -c ../.golangci.yml && cd ..
